/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Turno;
import Control.GestorBedel;
import bd.model.Bedel;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author rodri
 */
public class ModificarBedel extends javax.swing.JFrame {

    String passBedel;
    
    
    /**
     * Creates new form MODIFICAR_BEDEL
     */
    public ModificarBedel(Bedel bedel) {
        initComponents();
        this.setVisible(true);
        nombreTextField.setText(bedel.getNombre());
        apellidoTextField.setText(bedel.getApellido());
        idTextField.setText(bedel.getNombreUsuario());
        passBedel = bedel.getPassword();
        //passwordField1.setText(passBedel);
        //passwordField2.setText(passBedel);
        String turno = bedel.getTurno().charAt(0) + "" + bedel.getTurno().toLowerCase().subSequence(1, bedel.getTurno().length());
        jComboBox2.setSelectedItem(turno);
        this.setLocationRelativeTo(null);

        nombreTextField.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (nombreTextField.getText().length() >= 20) {
                    e.consume();
                }
            }
        });

        apellidoTextField.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (apellidoTextField.getText().length() >= 20) {
                    e.consume();
                }
            }
        });

        idTextField.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (idTextField.getText().length() >= 32) {
                    e.consume();
                }
            }
        });
        
        passwordField1.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (passwordField1.getText().length() >= 32) {
                    e.consume();
                }
            }
        });
        
        passwordField2.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (passwordField2.getText().length() >= 32) {
                    e.consume();
                }
            }
        });

    }

    public void errorNombre() {
        jLabel2.setForeground(Color.red);
    }

    public void errorUsuario() {
        jLabel5.setForeground(Color.red);
    }

    public void errorApellido() {
        jLabel3.setForeground(Color.red);
    }

    public void errorContra() {
        jLabel6.setForeground(Color.red);
    }

    public void errorContra2() {
        jLabel7.setForeground(Color.red);
    }

    public void errorTurno() {
        jLabel4.setForeground(Color.red);
    }

    public void nombreOk() {
        jLabel2.setForeground(Color.black);
    }

    public void usuarioOk() {
        jLabel5.setForeground(Color.black);
    }

    public void apellidoOk() {
        jLabel3.setForeground(Color.black);
    }

    public void contraOk() {
        jLabel6.setForeground(Color.black);
    }

    public void contra2Ok() {
        jLabel7.setForeground(Color.black);
    }

    public void turnoOk() {
        jLabel4.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellidoTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        passwordField1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        passwordField2 = new javax.swing.JPasswordField();
        modificarButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Bedel");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Modificar bedel");

        jLabel2.setText("Nombre");

        nombreTextField.setText("Nombre_Bedel");
        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido");

        apellidoTextField.setText("Apellido_Bedel");
        apellidoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Turno de trabajo");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mañana", "Tarde", "Noche" }));

        jLabel5.setText("ID Usuario");

        idTextField.setText("XXXXXX");
        idTextField.setEnabled(false);
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Contraseña");

        jLabel7.setText("Repetir contraseña");

        modificarButton.setBackground(new java.awt.Color(204, 204, 204));
        modificarButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        modificarButton.setText("Modificar");
        modificarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Cancelar");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jLabel1)
                .addGap(298, 298, 298))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(apellidoTextField)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modificarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(passwordField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void apellidoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoTextFieldActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed

        ArrayList<Boolean> datosError = new ArrayList<>();
        boolean datosInvalidos = true;
        //se inicializa el arreglo de tipos de error
        for (int i = 0; i < 8; i++) {
            datosError.add(false);
        }
        GestorBedel controlador = new GestorBedel();
        if (passwordField1.getText().isEmpty() && passwordField1.getText().isEmpty()) {
            datosInvalidos = controlador.validar(nombreTextField.getText(), apellidoTextField.getText(),
                    Turno.valueOf(jComboBox2.getSelectedItem().toString().toUpperCase()),
                    datosError, idTextField.getText());
        } else {
            datosInvalidos = controlador.validar(nombreTextField.getText(), apellidoTextField.getText(),
                    Turno.valueOf(jComboBox2.getSelectedItem().toString().toUpperCase()), passwordField1.getText(),
                    passwordField2.getText(), datosError, idTextField.getText());
        }

        if (datosError.get(6)) {
            jLabel9.setText("Solo letras");
            jLabel2.setForeground(Color.red);
        } else {
            jLabel9.setText("");
            jLabel2.setForeground(Color.black);
        }
        if (datosError.get(7)) {
            jLabel10.setText("Solo letras");
            jLabel3.setForeground(Color.red);
        } else {
            jLabel10.setText("");
            jLabel3.setForeground(Color.black);
        }

        //se colorean los datos invalidos
        if (datosError.get(0)) {
            errorNombre();
        } else {
            nombreOk();
        }
        if (datosError.get(1)) {
            errorApellido();
        } else {
            apellidoOk();
        }
        if (datosError.get(2)) {
            errorUsuario();
        } else {
            usuarioOk();
        }
        if (datosError.get(3)) {
            errorTurno();
        } else {
            turnoOk();
        }
        if (datosError.get(4)) {
            errorContra();
        } else {
            contraOk();
        }
        if (datosError.get(5)) {
            errorContra2();
        } else {
            contra2Ok();
        }

        if (!datosInvalidos) {
            Exito bien = new Exito();
            bien.setVisible(true);
            java.util.Date fecha = new Date();
            String fechaFormat = new SimpleDateFormat("dd/MM/yyyy").format(fecha);
            if (passwordField1.getText().isEmpty() && passwordField1.getText().isEmpty()) {
                controlador.modificarBedelSinPass(idTextField.getText(), nombreTextField.getText(), 
                        apellidoTextField.getText(), passBedel, 
                        Turno.valueOf(jComboBox2.getSelectedItem().toString().toUpperCase()).toString(), fechaFormat);
            } else {
                controlador.modificarBedel(idTextField.getText(), nombreTextField.getText(), 
                        apellidoTextField.getText(), passwordField1.getText(), 
                        Turno.valueOf(jComboBox2.getSelectedItem().toString().toUpperCase()).toString(), fechaFormat);
            } 
            this.dispose();
        }
    }//GEN-LAST:event_modificarButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CONFIRMACION_CANCELACION v3 = new CONFIRMACION_CANCELACION(this);
        v3.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton modificarButton;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JPasswordField passwordField2;
    // End of variables declaration//GEN-END:variables

}
