/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import bd.model.Reserva;
import bd.model.Diareserva;
import bd.model.DiareservaId;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author rodri
 */
public class NuevoDia extends javax.swing.JFrame {

    private Date fechaInicio;
    private Date fechaFin;
    private RegistrarReserva ventana;
    private Reserva reserva;

    private final ArrayList<String> cola;

    public NuevoDia(Reserva res, Date inicio, Date fin, RegistrarReserva vent) {
        initComponents();
        reserva = res;
        fechaInicio = inicio;
        fechaFin = fin;
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        fechaDateChooser.setCalendar(Calendar.getInstance());
        cola = new ArrayList<>();
        ventana = vent;

        this.cola.add("08:00");
        this.cola.add("08:30");
        this.cola.add("09:00");
        this.cola.add("09:30");
        this.cola.add("10:00");
        this.cola.add("10:30");
        this.cola.add("11:00");
        this.cola.add("11:30");
        this.cola.add("12:00");
        this.cola.add("12:30");
        this.cola.add("13:00");
        this.cola.add("13:30");
        this.cola.add("14:00");
        this.cola.add("14:30");
        this.cola.add("15:00");
        this.cola.add("15:30");
        this.cola.add("16:00");
        this.cola.add("16:30");
        this.cola.add("17:00");
        this.cola.add("17:30");
        this.cola.add("18:00");
        this.cola.add("18:30");
        this.cola.add("19:00");
        this.cola.add("19:30");
        this.cola.add("20:00");
        this.cola.add("20:30");
        this.cola.add("21:00");
        this.cola.add("21:30");
        this.cola.add("22:00");
        this.cola.add("22:30");
        this.cola.add("23:00");
        this.cola.add("23:30");
        
    this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        horaInicioComboBox = new javax.swing.JComboBox<>();
        horaFinCombobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        AceptarButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fechaDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo dia");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        horaInicioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30" }));
        horaInicioComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        horaInicioComboBox.setPreferredSize(new java.awt.Dimension(74, 20));
        horaInicioComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaInicioComboBoxActionPerformed(evt);
            }
        });

        horaFinCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30" }));
        horaFinCombobox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        horaFinCombobox.setPreferredSize(new java.awt.Dimension(74, 20));

        jLabel1.setText("Fecha");

        AceptarButton.setBackground(new java.awt.Color(204, 204, 204));
        AceptarButton.setText("Aceptar");
        AceptarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AceptarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar\n");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Error de fecha");

        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Error de horario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(horaInicioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(horaFinCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AceptarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horaFinCombobox, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel1))
                        .addComponent(fechaDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(horaInicioComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarButtonActionPerformed
        // COMPORTAMIENTO DEL BOTÓN ACEPTAR

        if (fechaDateChooser.getDate().compareTo(this.fechaInicio) != 1 || fechaDateChooser.getDate().compareTo(this.fechaFin) != -1) {
            //ERROR DE FECHA, SOLO INFORMO
            jLabel2.setVisible(true);
            if (this.cola.indexOf(horaInicioComboBox.getSelectedItem().toString()) >= this.cola.indexOf(horaFinCombobox.getSelectedItem().toString())) {
                jLabel3.setVisible(true); //TODO MAL, 2 ERRORES EN PANTALLA
            } else {
                jLabel3.setVisible(false);
            }
        } else {
            jLabel2.setVisible(false);

            if (this.cola.indexOf(horaInicioComboBox.getSelectedItem().toString()) >= this.cola.indexOf(horaFinCombobox.getSelectedItem().toString())) {
                jLabel3.setVisible(true);
            } else {

                jLabel3.setVisible(false); //TODO OK, FECHA Y HORA, AGREGAR DIARESERVA A LA LISTA

                Date fechaAux = fechaDateChooser.getDate();

                // Display a date in day, month, year format
                DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                String fecha = formatter.format(fechaAux);

                DiareservaId idAux = new DiareservaId(fecha, horaInicioComboBox.getSelectedItem().toString(), horaFinCombobox.getSelectedItem().toString(), ventana.reserva.getId());

                Diareserva dia = new Diareserva(idAux, reserva);
                dia.getId().setIdReserva(reserva.getId());

                ArrayList<Diareserva> listaIds1 = new ArrayList<>(reserva.getDiareservas());
                ArrayList<DiareservaId> listaIds2 = new ArrayList<>();
                for (int i = 0; i < listaIds1.size(); i++) {
                    listaIds2.add(listaIds1.get(i).getId());
                }
                if (listaIds2.contains(dia.getId())) {
                    DIA_YA_EXISTE vent = new DIA_YA_EXISTE();
                    vent.setVisible(true);
                } else {
                    reserva.diareservas.add(dia);//agrego el dia
                    ventana.agregarFilaATabla(dia);
                }
            }
        }
        //ventana.actualizarDiasReserva(diasReserva);//se actualiza la lista en la ventana original
    }//GEN-LAST:event_AceptarButtonActionPerformed

    private void horaInicioComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaInicioComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaInicioComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarButton;
    private com.toedter.calendar.JDateChooser fechaDateChooser;
    private javax.swing.JComboBox<String> horaFinCombobox;
    private javax.swing.JComboBox<String> horaInicioComboBox;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
