package bd.model;
// Generated 14-dic-2017 17:25:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aulamm generated by hbm2java
 */
public class Aulamm  implements java.io.Serializable {


     private String id;
     private Aula aula;
     private byte[] computadora;
     private byte[] televisor;
     private byte[] dvd;
     private Set posees = new HashSet(0);

    public Aulamm() {
    }

	
    public Aulamm(Aula aula, byte[] computadora, byte[] televisor, byte[] dvd) {
        this.aula = aula;
        this.computadora = computadora;
        this.televisor = televisor;
        this.dvd = dvd;
    }
    public Aulamm(Aula aula, byte[] computadora, byte[] televisor, byte[] dvd, Set posees) {
       this.aula = aula;
       this.computadora = computadora;
       this.televisor = televisor;
       this.dvd = dvd;
       this.posees = posees;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }
    public byte[] getComputadora() {
        return this.computadora;
    }
    
    public void setComputadora(byte[] computadora) {
        this.computadora = computadora;
    }
    public byte[] getTelevisor() {
        return this.televisor;
    }
    
    public void setTelevisor(byte[] televisor) {
        this.televisor = televisor;
    }
    public byte[] getDvd() {
        return this.dvd;
    }
    
    public void setDvd(byte[] dvd) {
        this.dvd = dvd;
    }
    public Set getPosees() {
        return this.posees;
    }
    
    public void setPosees(Set posees) {
        this.posees = posees;
    }




}


