package bd.model;
// Generated 14-dic-2017 19:22:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aulamm generated by hbm2java
 */
public class Aulamm  implements java.io.Serializable {


     private String id;
     private Aula aula;
     private boolean computadora;
     private boolean televisor;
     private boolean dvd;
     private Set posees = new HashSet(0);

    public Aulamm() {
    }

	
    public Aulamm(Aula aula, boolean computadora, boolean televisor, boolean dvd) {
        this.aula = aula;
        this.computadora = computadora;
        this.televisor = televisor;
        this.dvd = dvd;
    }
    public Aulamm(Aula aula, boolean computadora, boolean televisor, boolean dvd, Set posees) {
       this.aula = aula;
       this.computadora = computadora;
       this.televisor = televisor;
       this.dvd = dvd;
       this.posees = posees;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }
    public boolean isComputadora() {
        return this.computadora;
    }
    
    public void setComputadora(boolean computadora) {
        this.computadora = computadora;
    }
    public boolean isTelevisor() {
        return this.televisor;
    }
    
    public void setTelevisor(boolean televisor) {
        this.televisor = televisor;
    }
    public boolean isDvd() {
        return this.dvd;
    }
    
    public void setDvd(boolean dvd) {
        this.dvd = dvd;
    }
    public Set getPosees() {
        return this.posees;
    }
    
    public void setPosees(Set posees) {
        this.posees = posees;
    }




}


