package bd.model;
// Generated 24-oct-2017 11:41:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aulamm generated by hbm2java
 */
public class Aulamm  implements java.io.Serializable {


     private Integer id;
     private int capacidad;
     private String pizzaron;
     private byte[] habilitada;
     private byte[] cañon;
     private byte[] ac;
     private byte[] ubicacion;
     private byte[] computadora;
     private byte[] televisor;
     private byte[] dvd;
     private Set posees = new HashSet(0);

    public Aulamm() {
    }

	
    public Aulamm(int capacidad, String pizzaron, byte[] habilitada, byte[] cañon, byte[] ac, byte[] ubicacion, byte[] computadora, byte[] televisor, byte[] dvd) {
        this.capacidad = capacidad;
        this.pizzaron = pizzaron;
        this.habilitada = habilitada;
        this.cañon = cañon;
        this.ac = ac;
        this.ubicacion = ubicacion;
        this.computadora = computadora;
        this.televisor = televisor;
        this.dvd = dvd;
    }
    public Aulamm(int capacidad, String pizzaron, byte[] habilitada, byte[] cañon, byte[] ac, byte[] ubicacion, byte[] computadora, byte[] televisor, byte[] dvd, Set posees) {
       this.capacidad = capacidad;
       this.pizzaron = pizzaron;
       this.habilitada = habilitada;
       this.cañon = cañon;
       this.ac = ac;
       this.ubicacion = ubicacion;
       this.computadora = computadora;
       this.televisor = televisor;
       this.dvd = dvd;
       this.posees = posees;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }
    public String getPizzaron() {
        return this.pizzaron;
    }
    
    public void setPizzaron(String pizzaron) {
        this.pizzaron = pizzaron;
    }
    public byte[] getHabilitada() {
        return this.habilitada;
    }
    
    public void setHabilitada(byte[] habilitada) {
        this.habilitada = habilitada;
    }
    public byte[] getCañon() {
        return this.cañon;
    }
    
    public void setCañon(byte[] cañon) {
        this.cañon=cañon;
    }
    public byte[] getAc() {
        return this.ac;
    }
    
    public void setAc(byte[] ac) {
        this.ac = ac;
    }
    public byte[] getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(byte[] ubicacion) {
        this.ubicacion = ubicacion;
    }
    public byte[] getComputadora() {
        return this.computadora;
    }
    
    public void setComputadora(byte[] computadora) {
        this.computadora = computadora;
    }
    public byte[] getTelevisor() {
        return this.televisor;
    }
    
    public void setTelevisor(byte[] televisor) {
        this.televisor = televisor;
    }
    public byte[] getDvd() {
        return this.dvd;
    }
    
    public void setDvd(byte[] dvd) {
        this.dvd = dvd;
    }
    public Set getPosees() {
        return this.posees;
    }
    
    public void setPosees(Set posees) {
        this.posees = posees;
    }




}


