package bd.model;
// Generated 13-dic-2017 23:20:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Diareserva generated by hbm2java
 */
public class Diareserva  implements java.io.Serializable {


     private DiareservaId id;
     private Aula aula;
     private Reserva reserva;
     private Set posees = new HashSet(0);
     private Set tienediareservas = new HashSet(0);

    public Diareserva() {
    }

	
    public Diareserva(DiareservaId id, Aula aula, Reserva reserva) {
        this.id = id;
        this.aula = aula;
        this.reserva = reserva;
    }
    public Diareserva(DiareservaId id, Aula aula, Reserva reserva, Set posees, Set tienediareservas) {
       this.id = id;
       this.aula = aula;
       this.reserva = reserva;
       this.posees = posees;
       this.tienediareservas = tienediareservas;
    }
   
    public DiareservaId getId() {
        return this.id;
    }
    
    public void setId(DiareservaId id) {
        this.id = id;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public Set getPosees() {
        return this.posees;
    }
    
    public void setPosees(Set posees) {
        this.posees = posees;
    }
    public Set getTienediareservas() {
        return this.tienediareservas;
    }
    
    public void setTienediareservas(Set tienediareservas) {
        this.tienediareservas = tienediareservas;
    }




}


