package bd.model;
// Generated 16-dic-2017 9:38:19 by Hibernate Tools 4.3.1

/**
 * Diareserva generated by hbm2java
 */
public class Diareserva implements java.io.Serializable {

    private DiareservaId id;
    private Aula idAula;
    private Reserva reserva;

    public Diareserva() {
    }

    public Aula getIdAula() {
        return idAula;
    }

    public Diareserva(DiareservaId id, Aula aula, Reserva reserva) {
        this.id = id;
        this.idAula = aula;
        this.reserva = reserva;
    }

    public void setIdAula(Aula idAula) {
        this.idAula = idAula;
    }

    public Diareserva(DiareservaId id, Reserva reserva) {
        this.id = id;
        this.reserva = reserva;
    }

    public DiareservaId getId() {
        return this.id;
    }

    public void setId(DiareservaId id) {
        this.id = id;
    }

    public Aula getAula() {
        return this.idAula;
    }

    public void setAula(Aula aula) {
        this.idAula = aula;
    }

    public Reserva getReserva() {
        return this.reserva;
    }

    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }

}
