package bd.model;
// Generated Dec 15, 2017 3:18:15 PM by Hibernate Tools 4.3.1



/**
 * Diareserva generated by hbm2java
 */
public class Diareserva  implements java.io.Serializable {


     private DiareservaId id;
     private Aula aula;
     private Reserva reserva;

    public Diareserva() {
    }

    public Diareserva(DiareservaId id, Aula aula, Reserva reserva) {
       this.id = id;
       this.aula = aula;
       this.reserva = reserva;
    }
   
    public DiareservaId getId() {
        return this.id;
    }
    
    public void setId(DiareservaId id) {
        this.id = id;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }




}


