package bd.model;
// Generated 18-oct-2017 21:28:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private int id;
     private String apellido;
     private String nombre;
     private String email;
     private Set tienedocentes = new HashSet(0);

    public Docente() {
    }

	
    public Docente(int id, String apellido, String nombre, String email) {
        this.id = id;
        this.apellido = apellido;
        this.nombre = nombre;
        this.email = email;
    }
    public Docente(int id, String apellido, String nombre, String email, Set tienedocentes) {
       this.id = id;
       this.apellido = apellido;
       this.nombre = nombre;
       this.email = email;
       this.tienedocentes = tienedocentes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getTienedocentes() {
        return this.tienedocentes;
    }
    
    public void setTienedocentes(Set tienedocentes) {
        this.tienedocentes = tienedocentes;
    }




}


