package bd.model;
// Generated 18-oct-2017 21:28:21 by Hibernate Tools 4.3.1



/**
 * Hace generated by hbm2java
 */
public class Hace  implements java.io.Serializable {


     private int idMaster;
     private Bedel bedel;
     private Reserva reserva;

    public Hace() {
    }

	
    public Hace(int idMaster) {
        this.idMaster = idMaster;
    }
    public Hace(int idMaster, Bedel bedel, Reserva reserva) {
       this.idMaster = idMaster;
       this.bedel = bedel;
       this.reserva = reserva;
    }
   
    public int getIdMaster() {
        return this.idMaster;
    }
    
    public void setIdMaster(int idMaster) {
        this.idMaster = idMaster;
    }
    public Bedel getBedel() {
        return this.bedel;
    }
    
    public void setBedel(Bedel bedel) {
        this.bedel = bedel;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }




}


