package bd.model;
// Generated Dec 15, 2017 3:18:15 PM by Hibernate Tools 4.3.1



/**
 * Historialdecontrasenia generated by hbm2java
 */
public class Historialdecontrasenia  implements java.io.Serializable {


     private int value;
     private Bedel bedel;
     private Integer fecha;
     private Integer actual;

    public Historialdecontrasenia() {
    }

	
    public Historialdecontrasenia(int value) {
        this.value = value;
    }
    public Historialdecontrasenia(int value, Bedel bedel, Integer fecha, Integer actual) {
       this.value = value;
       this.bedel = bedel;
       this.fecha = fecha;
       this.actual = actual;
    }
   
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }
    public Bedel getBedel() {
        return this.bedel;
    }
    
    public void setBedel(Bedel bedel) {
        this.bedel = bedel;
    }
    public Integer getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Integer fecha) {
        this.fecha = fecha;
    }
    public Integer getActual() {
        return this.actual;
    }
    
    public void setActual(Integer actual) {
        this.actual = actual;
    }




}


