package bd.model;
// Generated 16-dic-2017 9:38:19 by Hibernate Tools 4.3.1



/**
 * Historialdecontrasenia generated by hbm2java
 */
public class Historialdecontrasenia  implements java.io.Serializable {


     private Integer id;
     private Bedel bedel;
     private String fecha;
     private String value;

    public Historialdecontrasenia() {
    }

	
    public Historialdecontrasenia(String value) {
        this.value = value;
    }
    public Historialdecontrasenia(Bedel bedel, String fecha, String value) {
       this.bedel = bedel;
       this.fecha = fecha;
       this.value = value;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Bedel getBedel() {
        return this.bedel;
    }
    
    public void setBedel(Bedel bedel) {
        this.bedel = bedel;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


