package bd.model;
// Generated 14-dic-2017 17:53:50 by Hibernate Tools 4.3.1



/**
 * Politicaseguridad generated by hbm2java
 */
public class Politicaseguridad  implements java.io.Serializable {


     private Integer id;
     private Integer longmin;
     private Integer longmax;

    public Politicaseguridad() {
    }

    public Politicaseguridad(Integer longmin, Integer longmax) {
       this.longmin = longmin;
       this.longmax = longmax;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getLongmin() {
        return this.longmin;
    }
    
    public void setLongmin(Integer longmin) {
        this.longmin = longmin;
    }
    public Integer getLongmax() {
        return this.longmax;
    }
    
    public void setLongmax(Integer longmax) {
        this.longmax = longmax;
    }




}


