package bd.model;
// Generated Dec 15, 2017 3:18:15 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private int id;
     private Docente docente;
     private String tipoAula;
     private int cantidadAlumnos;
     private String nombreCurso;
     private String periodo;
     public Set diareservas = new HashSet(0);
     private Set haces = new HashSet(0);

    public Reserva() {
    }

	
    public Reserva(int id, Docente docente, String tipoAula, int cantidadAlumnos, String nombreCurso, String periodo) {
        this.id = id;
        this.docente = docente;
        this.tipoAula = tipoAula;
        this.cantidadAlumnos = cantidadAlumnos;
        this.nombreCurso = nombreCurso;
        this.periodo = periodo;
    }
    public Reserva(int id, Docente docente, String tipoAula, int cantidadAlumnos, String nombreCurso, String periodo, Set diareservas, Set haces) {
       this.id = id;
       this.docente = docente;
       this.tipoAula = tipoAula;
       this.cantidadAlumnos = cantidadAlumnos;
       this.nombreCurso = nombreCurso;
       this.periodo = periodo;
       this.diareservas = diareservas;
       this.haces = haces;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public String getTipoAula() {
        return this.tipoAula;
    }
    
    public void setTipoAula(String tipoAula) {
        this.tipoAula = tipoAula;
    }
    public int getCantidadAlumnos() {
        return this.cantidadAlumnos;
    }
    
    public void setCantidadAlumnos(int cantidadAlumnos) {
        this.cantidadAlumnos = cantidadAlumnos;
    }
    public String getNombreCurso() {
        return this.nombreCurso;
    }
    
    public void setNombreCurso(String nombreCurso) {
        this.nombreCurso = nombreCurso;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public Set getDiareservas() {
        return  this.diareservas;
    }
    
    public void setDiareservas(Set diareservas) {
        this.diareservas = diareservas;
    }
    public Set getHaces() {
        return this.haces;
    }
    
    public void setHaces(Set haces) {
        this.haces = haces;
    }




}


