package bd.model;
// Generated 14-dic-2017 11:50:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private int id;
     private String tipoAula;
     private int cantidadAlumnos;
     private String nombreCurso;
     private String periodo;
     private Set diareservas = new HashSet(0);
     private Set haces = new HashSet(0);
     private Set tienediareservas = new HashSet(0);
     private Set tienedocentes = new HashSet(0);

    public Reserva() {
    }

	
    public Reserva(int id, String tipoAula, int cantidadAlumnos, String nombreCurso, String periodo) {
        this.id = id;
        this.tipoAula = tipoAula;
        this.cantidadAlumnos = cantidadAlumnos;
        this.nombreCurso = nombreCurso;
        this.periodo = periodo;
    }
    public Reserva(int id, String tipoAula, int cantidadAlumnos, String nombreCurso, String periodo, Set diareservas, Set haces, Set tienediareservas, Set tienedocentes) {
       this.id = id;
       this.tipoAula = tipoAula;
       this.cantidadAlumnos = cantidadAlumnos;
       this.nombreCurso = nombreCurso;
       this.periodo = periodo;
       this.diareservas = diareservas;
       this.haces = haces;
       this.tienediareservas = tienediareservas;
       this.tienedocentes = tienedocentes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTipoAula() {
        return this.tipoAula;
    }
    
    public void setTipoAula(String tipoAula) {
        this.tipoAula = tipoAula;
    }
    public int getCantidadAlumnos() {
        return this.cantidadAlumnos;
    }
    
    public void setCantidadAlumnos(int cantidadAlumnos) {
        this.cantidadAlumnos = cantidadAlumnos;
    }
    public String getNombreCurso() {
        return this.nombreCurso;
    }
    
    public void setNombreCurso(String nombreCurso) {
        this.nombreCurso = nombreCurso;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public Set getDiareservas() {
        return this.diareservas;
    }
    
    public void setDiareservas(Set diareservas) {
        this.diareservas = diareservas;
    }
    public Set getHaces() {
        return this.haces;
    }
    
    public void setHaces(Set haces) {
        this.haces = haces;
    }
    public Set getTienediareservas() {
        return this.tienediareservas;
    }
    
    public void setTienediareservas(Set tienediareservas) {
        this.tienediareservas = tienediareservas;
    }
    public Set getTienedocentes() {
        return this.tienedocentes;
    }
    
    public void setTienedocentes(Set tienedocentes) {
        this.tienedocentes = tienedocentes;
    }




}


