package bd.model;
// Generated 18-oct-2017 21:28:21 by Hibernate Tools 4.3.1



/**
 * Tienedocente generated by hbm2java
 */
public class Tienedocente  implements java.io.Serializable {


     private int idMaster;
     private Docente docente;
     private Reserva reserva;

    public Tienedocente() {
    }

    public Tienedocente(int idMaster, Docente docente, Reserva reserva) {
       this.idMaster = idMaster;
       this.docente = docente;
       this.reserva = reserva;
    }
   
    public int getIdMaster() {
        return this.idMaster;
    }
    
    public void setIdMaster(int idMaster) {
        this.idMaster = idMaster;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }




}


