package bd.model;
// Generated 18-oct-2017 21:28:21 by Hibernate Tools 4.3.1



/**
 * Tienediareserva generated by hbm2java
 */
public class Tienediareserva  implements java.io.Serializable {


     private int idMaster;
     private Diareserva diareserva;
     private Reserva reserva;

    public Tienediareserva() {
    }

    public Tienediareserva(int idMaster, Diareserva diareserva, Reserva reserva) {
       this.idMaster = idMaster;
       this.diareserva = diareserva;
       this.reserva = reserva;
    }
   
    public int getIdMaster() {
        return this.idMaster;
    }
    
    public void setIdMaster(int idMaster) {
        this.idMaster = idMaster;
    }
    public Diareserva getDiareserva() {
        return this.diareserva;
    }
    
    public void setDiareserva(Diareserva diareserva) {
        this.diareserva = diareserva;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }




}


